version: '3'
services:
  redis:
    image: docker.io/bitnami/redis:6.2
    container_name: equeue_redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - 6379:6379
